#include <iostream>
#include <fstream>
#include <vector>
#include <climits>
#include <chrono>
#include <algorithm>
using namespace std;
 
//Bellman-Ford Algorithm
//Uses ChatGBT to help correct mistakes and solve issues missed
//reads the graph generated by dataGeneration.cpp (thePoints.dat)
//finds the shortest path from node 0 (0,0) to node 299 (99,99)
//uses Manhattan distance as edge weights (|dx| + |dy|)
 
struct Point {
    int x, y;
    int neighbors[4];   // up to 4 neighbors per node (indices into points[])
};
 
struct Edge {
    int src, dst, weight;
};
 
//manhattan distance between two points
int manhattanDist(const Point& a, const Point& b) {
    return abs(a.x - b.x) + abs(a.y - b.y);
}
 
//load graph from thePoints.dat produced by dataGeneration.cpp
//format per line: x y neighbor1 neighbor2 neighbor3 neighbor4
bool loadGraph(const string& filename, vector<Point>& points, vector<Edge>& edges) {
    ifstream file(filename);
    if (!file.is_open()) {
        cerr << "Error: could not open '" << filename << "'\n";
        cerr << "Make sure to run dataGeneration first to produce thePoints.dat\n";
        return false;
    }
 
    points.resize(300);
    for (int i = 0; i < 300; i++) {
        file >> points[i].x >> points[i].y
             >> points[i].neighbors[0] >> points[i].neighbors[1]
             >> points[i].neighbors[2] >> points[i].neighbors[3];
    }
    file.close();
 
    //builds edge list (undirected, skip -1 sentinels)
    for (int i = 0; i < 300; i++) {
        for (int k = 0; k < 4; k++) {
            int j = points[i].neighbors[k];
            if (j == -1) continue;
            int w = manhattanDist(points[i], points[j]);
            edges.push_back({i, j, w});
        }
    }
 
    return true;
}
 
//bellman-Ford algorithm
bool bellmanFord(const vector<Point>& points,
                 const vector<Edge>& edges,
                 int src,
                 vector<int>& dist,
                 vector<int>& pred)
{
    int V = (int)points.size();
    dist.assign(V, INT_MAX);
    pred.assign(V, -1);
    dist[src] = 0;

    for (int iter = 0; iter < V - 1; iter++) {
        bool updated = false;
        for (const Edge& e : edges) {
            if (dist[e.src] == INT_MAX) continue;
            int newDist = dist[e.src] + e.weight;
            if (newDist < dist[e.dst]) {
                dist[e.dst] = newDist;
                pred[e.dst] = e.src;
                updated = true;
            }
        }
        if (!updated) break;
    }
 
    //checks for negative cycles (one extra pass)
    for (const Edge& e : edges) {
        if (dist[e.src] == INT_MAX) continue;
        if (dist[e.src] + e.weight < dist[e.dst]) {
            cerr << "Warning: negative cycle detected!\n";
            return false;
        }
    }
 
    return true;
}
 
vector<int> reconstructPath(const vector<int>& pred, int src, int dst) {
    vector<int> path;
    for (int cur = dst; cur != -1; cur = pred[cur]) {
        path.push_back(cur);
        if (cur == src) break;
    }
    reverse(path.begin(), path.end());
    if (path.empty() || path[0] != src) return {};
    return path;
}
 
int main() {
    const string dataFile = "thePoints.dat";
    const string outFile  = "bellmanFord_result.txt";
    const int SRC = 0;    // (0,0)
    const int DST = 299;  // (99,99)
 
    //loads graph
    vector<Point> points;
    vector<Edge>  edges;
 
    if (!loadGraph(dataFile, points, edges)) return 1;
 
    //runs Bellman-Ford
    auto start = chrono::high_resolution_clock::now();
 
    vector<int> dist, pred;
    bool ok = bellmanFord(points, edges, SRC, dist, pred);
 
    auto end = chrono::high_resolution_clock::now();
    double ms = chrono::duration<double, milli>(end - start).count();
 
    if (!ok) {
        cerr << "Bellman-Ford failed (negative cycle). Exiting.\n";
        return 1;
    }
 
    //writes all results to file
    ofstream out(outFile);
 
    out << "Bellman-Ford Shortest Path\n\n";
 
    out << "Graph loaded from : " << dataFile << "\n";
    out << "Nodes             : " << points.size() << "\n";
    out << "Directed edges    : " << edges.size() << "\n\n";
 
    out << "Source      : node " << SRC << " (" << points[SRC].x << "," << points[SRC].y << ")\n";
    out << "Destination : node " << DST << " (" << points[DST].x << "," << points[DST].y << ")\n\n";
 
    out << "--- Results\n";
    if (dist[DST] == INT_MAX) {
        out << "No path found from node " << SRC << " to node " << DST << "\n";
    } else {
        out << "Shortest distance : " << dist[DST] << " (Manhattan units)\n";
        out << "Expected minimum  : 198 (Manhattan distance from (0,0) to (99,99))\n";
        out << "Runtime           : " << ms << " ms\n\n";
 
        vector<int> path = reconstructPath(pred, SRC, DST);
        if (path.empty()) {
            out << "Could not reconstruct path.\n";
        } else {
            out << "Path (" << path.size() << " nodes):\n";
            for (int i = 0; i < (int)path.size(); i++) {
                int idx = path[i];
                out << "  [" << idx << "] ("
                    << points[idx].x << "," << points[idx].y << ")";
                if (i + 1 < (int)path.size()) {
                    int nxt = path[i+1];
                    out << "  --" << manhattanDist(points[idx], points[nxt]) << "--> ";
                }
                out << "\n";
            }
        }
    }
 
    return 0;
}
